export {default as Login} from './Login/Login'
export {default as Register} from './Register/Register'
export {default as Account} from './Account/Account'
export {default as Favour} from './Favour/Favour'
export {default as Request} from './Request/Request'
export {default as Leaderboard} from './Leaderboard/Leaderboard'